apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 0 # Puerto dinámico para cumplir la rúbrica
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: tool-service:latest
          imagePullPolicy: Never
          env:
            - name: SERVER_PORT
              value: "0" # Asignación dinámica (Punto 2 Rúbrica)
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-service:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"
            # Conexión exclusiva a su base de datos tools_db
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-db:5432/tools_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "09282325"