server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: amounts-service
          uri: lb://amounts-service
          predicates:
            - Path=/amounts/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/tools/**
        - id: loans-service
          uri: lb://loans-service
          predicates:
            - Path=/loans/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: kardex-service
          uri: lb://kardexAndMovements-service
          predicates:
            - Path=/movements/**
        - id: reports-service
          uri: lb://reports-service
          predicates:
            - Path=/reports-service/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**