server:
  port: 8090 # El puerto externo del container

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # ✅ ESTA ES LA MAGIA PARA CORS (Adaptado a tu local)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173" # Tu Frontend React
              - "http://localhost:3000" # Por si acaso
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
              - "PATCH"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: amounts-service
          uri: lb://amounts-service
          predicates:
            - Path=/amounts/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/tools/**
        - id: loans-service
          uri: lb://loans-service
          predicates:
            - Path=/loans/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: kardex-service
          uri: lb://kardexAndMovements-service # Recuerda renombrar tu bootstrap.yaml o el id aquí
          predicates:
            - Path=/movements/**
        - id: reports-service
          uri: lb://reports-service
          predicates:
            - Path=/reports-service/** # Ojo con el path, a veces es solo /reports/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**