server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: tool-service
          uri: lb://tool-service  # "lb" significa Load Balancer (Balanceo de carga usando Eureka)
          predicates:
            - Path=/tool/** # Si escribes localhost:8080/tool/..., te lleva a tool-service