server:
  port: ${PORT:${SERVER_PORT:0}}  # Tu configuración avanzada

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  datasource:
    # Configuración de PostgreSQL (Esto faltaba en tu ejemplo)
    url: jdbc:postgresql://localhost:5432/tools_db
    username: postgres
    password: "09282325"  # Tu contraseña
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true